### Register a user
POST http://localhost:8800/api/auth/register 
Content-Type: application/json

    {
        "username":"Manish",
        "email":"m@gmail.com",
        "password":"manish26"
    }

### login a user

POST http://localhost:8800/api/auth/login 
Content-Type: application/json

    {
        "username":"Manish",
        "email":"m@gmail.com",
        "password":"manish26"
    }